/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author amila
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usersbox = new javax.swing.JButton();
        customersbox = new javax.swing.JButton();
        productsbox = new javax.swing.JButton();
        ordersbox = new javax.swing.JButton();
        orderdetailsbox = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 102), null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Clarendon Blk BT", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\5470133-removebg-preview.png")); // NOI18N
        jLabel1.setText("..Menu..");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        usersbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usersbox.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\Brown Organic Burger Presentation\\user.png")); // NOI18N
        usersbox.setText("Users");
        usersbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersboxActionPerformed(evt);
            }
        });
        jPanel3.add(usersbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 40));

        customersbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customersbox.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\Brown Organic Burger Presentation\\customer-review.png")); // NOI18N
        customersbox.setText("Customers");
        customersbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersboxActionPerformed(evt);
            }
        });
        jPanel3.add(customersbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, 40));

        productsbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productsbox.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\Brown Organic Burger Presentation\\checklist.png")); // NOI18N
        productsbox.setText("Products");
        productsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsboxActionPerformed(evt);
            }
        });
        jPanel3.add(productsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 40));

        ordersbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordersbox.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\Brown Organic Burger Presentation\\info.png")); // NOI18N
        ordersbox.setText("Orders");
        ordersbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersboxActionPerformed(evt);
            }
        });
        jPanel3.add(ordersbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 40));

        orderdetailsbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderdetailsbox.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\Brown Organic Burger Presentation\\cash-on-delivery.png")); // NOI18N
        orderdetailsbox.setText("Order Details");
        orderdetailsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderdetailsboxActionPerformed(evt);
            }
        });
        jPanel3.add(orderdetailsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 400));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHAMA COMPUTERS\\Downloads\\Brown Organic Burger Presentation\\10.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        setSize(new java.awt.Dimension(684, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void orderdetailsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderdetailsboxActionPerformed
        orderdetails m =  new orderdetails();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderdetailsboxActionPerformed

    private void ordersboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersboxActionPerformed
        orders m = new orders();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ordersboxActionPerformed

    private void productsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsboxActionPerformed
        products m = new products();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productsboxActionPerformed

    private void customersboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersboxActionPerformed
        customers x = new customers();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customersboxActionPerformed

    private void usersboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersboxActionPerformed

        users f = new users();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usersboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customersbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton orderdetailsbox;
    private javax.swing.JButton ordersbox;
    private javax.swing.JButton productsbox;
    private javax.swing.JButton usersbox;
    // End of variables declaration//GEN-END:variables
}
